### ISSUE TITLE
Transferring kubo NPM package name

### ISSUE THREAD

**Issue by lidel** [queerviolet/werkit#1]
Hi @queerviolet! 

GO-IPFS  project renamed to "Kubo" (https://github.com/ipfs/kubo/issues/8959) 
and are slowly migrating various packages to the new name.

We would like to rename our NPM package from https://www.npmjs.com/package/go-ipfs  to "kubo",
but it is already taken: https://www.npmjs.com/package/kubo

## Here comes the ask :pray: 

Since it is rather small demo package, and was not updated for the past 5 years,  and got renamed to "werkit" at some point(?),
would it be possible for you to donate  `kubo` NPM package to IPFS project (https://ipfs.tech/, https://github.com/ipfs) by adding [me](https://www.npmjs.com/~lidel) as a new Owner? :pray:

**Comment by lidel** [comment]
kind ping, @queerviolet

**Comment by SgtPooki** [comment]
@queerviolet you can transfer ownership easily via https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by queerviolet** [comment]
hi! thanks for your patience! yes, i would love to donate the name. i need
to get back to my computer tho, which won’t happen till wednesday. but i’m
happy to do it then.

**Comment by lidel** [comment]
@queerviolet hi, kind ping :) I'm https://www.npmjs.com/~lidel – if you add me as owner that should be enough to unblock us :) :pray:

**Comment by TinyTb** [comment]
@queerviolet you can add `lidel` as owner with:

```
npm owner add lidel kubo
```

Alternatively, you can use the npmjs.com UI linked earlier.

**Comment by achingbrain** [comment]
@queerviolet just catching up here - are you still willing to transfer ownership of the `kubo` repo on npm?

**Comment by queerviolet** [comment]
hey, sorry for the very long delay! i've added lidel as a maintainer.

**Comment by lidel** [comment]
Thank you @queerviolet! :heart: 

Rename chores will continue in https://github.com/ipfs/npm-go-ipfs/issues/51
